project:
  type: website
website:
  title: "digiHerb"
  favicon: images/logo.png
  page-navigation: true
  site-url: https://anders-kolstad.github.io/digiHerb
  repo-url: https://github.com/anders-kolstad/digiHerb
  repo-actions: [edit, source, issue]

      
format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: atom-one-dark
    toc: true
    grid:
      sidebar-width: 150px